### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Ovilia** [hexojs/hexo-uglify#2]
Hi, I installed this lib and added this in `_config.yml`:
```
uglify:
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'
```

But the js files under `themes` are not compressed to `public`. What should I do?
